# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch]
  pull_request:
    types: closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          email: gburrows@microsoft.com
          name: gburrows
          token: secrets.GITHUB_TOKEN
      
      - name: Get Latest Tag
        id: latestTag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        
      - name: Simple Semver
        id: semver
        uses: matt-FFFFFF/simple-semver@v0.1.0
        with:
          semver-input: steps.latestTag.outputs.tag
          increment: github.event.pull_request.labels.*.name

      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: steps.semver.outputs.semver
          
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
